export const GET_WORKOUTS = "GET_WORKOUTS";
export const CREATE_WORKOUT = "ADD_WORKOUT";
export const UPDATE_WORKOUT = "UPDATE_WORKOUT";
export const DELETE_WORKOUT = "DELETE_WORKOUT";
export const WORKOUTS_LOADING = "WORKOUTS_LOADING";
export const GET_WORKOUT_BY_ID = "GET_WORKOUT_BY_ID";
export const FETCH_USER = "FETCH_USER";
